---
version: '2.1'

services:
  postgres:
    image: 'postgres:latest'
    container_name: db_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 127.0.0.1:5432:5432
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: db_pgadmin
    environment:
      - "PGADMIN_DEFAULT_EMAIL=test@test.de"
      - "PGADMIN_DEFAULT_PASSWORD=1234"
    ports:
      - 127.0.0.1:8080:80
